server:
  port: 8000
spring:
  profiles:
    active: dev
    include: feign
  application:
    name: service-order
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      config:
        import-check: false
        namespace: ${spring.profiles.active:public}

logging:
  level:
    com.flittly.order.feign: DEBUG

---
spring:
  config:
    import:
      - optional:nacos:common.yml?group=order
      - optional:nacos:database.yml?group=order
    activate:
      on-profile: dev
---
spring:
  config:
    import:
      - optional:nacos:common.yml?group=order
      - optional:nacos:database.yml?group=order
    activate:
      on-profile: test
---
spring:
  config:
    import:
      - optional:nacos:common.yml?group=order
      - optional:nacos:database.yml?group=order
    activate:
      on-profile: prod